dbt_eric_coffeeshop:
  outputs:
    dev:
      dataset: dbt_erict
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: aec-students
      threads: 8
      type: bigquery
    ci:
      type: bigquery
      method: service-account
      project: aec-students
      dataset: dbt_erict
      threads: 8
      keyfile: ./dbt_eric_coffeeshop/gcp-credentials.json 
  target: dev
